"""Type stubs for sounddevice package"""
from typing import Any, Callable
import numpy as np
from numpy.typing import NDArray

class CallbackFlags:
    pass

class InputStream:
    def __init__(
        self,
        samplerate: float | None = None,
        channels: int | None = None,
        dtype: Any | None = None,
        blocksize: int | None = None,
        callback: Callable[[NDArray[Any], int, dict[str, Any], CallbackFlags], None] | None = None,
    ) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def close(self) -> None: ...
    def wait(self) -> None: ...
    def __enter__(self) -> "InputStream": ...
    def __exit__(self, *args: Any) -> None: ...

class OutputStream:
    def __init__(
        self,
        samplerate: float | None = None,
        channels: int | None = None,
        dtype: Any | None = None,
        blocksize: int | None = None,
        latency: str | float | None = None,
    ) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def close(self) -> None: ...
    def write(self, data: NDArray[Any]) -> None: ...
    def __enter__(self) -> "OutputStream": ...
    def __exit__(self, *args: Any) -> None: ...

def query_devices(kind: str | None = None) -> Any: ...
def query_devices(kind: str | None = None) -> list[dict[str, Any]]: ...
