"""Type stubs for numpy package"""
from typing import Any, overload
from numpy.typing import NDArray

# numpyモジュールの基本的な型定義
def array(object: Any, dtype: Any | None = None, copy: bool = True, order: str | None = None, subok: bool = False, ndmin: int = 0) -> NDArray[Any]: ...

@overload
def frombuffer(buffer: Any, dtype: Any, count: int = -1, offset: int = 0) -> NDArray[Any]: ...
def frombuffer(buffer: Any, dtype: Any, count: int = -1, offset: int = 0) -> NDArray[Any]: ...
def concatenate(arrays: Any, axis: int | None = 0, out: Any | None = None, dtype: Any | None = None, casting: str = "same_kind") -> NDArray[Any]: ...
def clip(a: Any, a_min: Any, a_max: Any, out: Any | None = None) -> NDArray[Any]: ...
def sqrt(x: Any, out: Any | None = None, where: Any = True, casting: str = "same_kind", order: str = "K", dtype: Any | None = None, subok: bool = True) -> NDArray[Any]: ...
def mean(a: Any, axis: Any | None = None, dtype: Any | None = None, out: Any | None = None, keepdims: bool = False, where: Any = True) -> Any: ...
def max(a: Any, axis: Any | None = None, out: Any | None = None, keepdims: bool = False, initial: Any | None = None, where: Any = True) -> Any: ...
def abs(x: Any, out: Any | None = None, where: Any = True, casting: str = "same_kind", order: str = "K", dtype: Any | None = None, subok: bool = True) -> NDArray[Any]: ...
def where(condition: Any, x: Any, y: Any) -> NDArray[Any]: ...

class dtype:
    float32: Any
    int16: Any
    float64: Any

float32: Any
int16: Any
float64: Any

